on:
    push:
      branches:
        - deploy/develop
    workflow_dispatch:

jobs:
    build-and-push-image:
        runs-on: ubuntu-latest
        permissions:
          contents: read
          packages: write
          attestations: write
          id-token: write
    
        steps:
          - name: Checkout repository
            uses: actions/checkout@v4
          
          - name: Log in to Docker Hub
            uses: docker/login-action@v3
            with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_PASSWORD }}
          
          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3
      
          - name: Build and push
            uses: docker/build-push-action@v6
            with:
              context: .
              push: true
              tags: huyhoang204205/tuitionfeemanagement:latest
              cache-from: type=registry,ref=huyhoang204205/tuitionfeemanagement:latest
              cache-to: type=inline

    deploy:
        needs: build-and-push-image
        runs-on: ubuntu-latest
        steps:
          - name: Checkout repository
            uses: actions/checkout@v4
            
          - name: Add SSH Key
            uses: webfactory/ssh-agent@v0.9.0
            with:
              ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
          - name: Add host to known_hosts
            run: |
              mkdir -p ~/.ssh
              ssh-keyscan -H 115.73.218.193 >> ~/.ssh/known_hosts
          
          - name: Connect, Pull, and Build Docker
            run: |
              ssh huyhoang204205@115.73.218.193 << EOF
                set -e
                cd /home/huyhoang204205/Documents/tuitionfeemanagement
                echo "${{ secrets.SSH_PASS }}" | sudo -S docker compose pull tuition-fee-frontend
                echo "${{ secrets.SSH_PASS }}" | sudo -S docker compose up -d
              EOF